import { Injectable } from '@angular/core'; 
import { RecruiterJob } from '../recruiter/models/recruiter.models';

/* ========================================
   MOCK SERVICE (SIMULA BANCO)
======================================== */
@Injectable({ providedIn: 'root' })
export class RecruiterMockService {

  /* ========================================
     GET JOBS + TALENTS
     (no futuro vira HttpClient)
  ======================================== */
  getJobsTalents(): RecruiterJob[] {
    
    return [
      {
        id: 'job-001',
        title: 'Desenvolvedor .NET Sênior',
        description: 'Atuação em APIs e microsserviços com foco em performance, arquitetura e evolução de produto.',
        department: 'Tecnologia',
        location: 'Rio de Janeiro',
        type: 'Remoto',
        status: 'aberta',
        createdAt: '2026-02-22T18:00:00Z',
        talents: [
          {
            id: 't1',
            name: 'Ana Martins',
            appliedAt: '2026-02-22T08:30:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 16:40',
            unreadCount: 2,
            lastMessage: 'Posso fazer remoto 100%?',
            messages: [],
          },
          {
            id: 't2',
            name: 'João Pedro',
            appliedAt: '2026-02-22T10:15:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 21:10',
            unreadCount: 0,
            lastMessage: 'Tenho portfólio, quer que eu envie?',
            messages: [],
          },
          {
            id: 't3',
            name: 'Julio Fazenda',
            appliedAt: '2026-02-22T13:05:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 09:12',
            unreadCount: 1,
            lastMessage: 'Perfeito, obrigado!',
            messages: [],
          },
        ],
      },

      {
        id: 'job-002',
        title: 'UX Designer',
        description: 'Responsável por fluxos de produto, protótipos e melhorias de experiência em jornadas críticas.',
        department: 'Produto',
        location: 'São Paulo',
        type: 'Híbrido',
        status: 'pausada',
        createdAt: '2026-02-20T18:00:00Z',
        talents: [
          {
            id: 't4',
            name: 'Bruna Lima',
            appliedAt: '2026-02-20T14:20:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 11:02',
            unreadCount: 0,
            lastMessage: 'Enviei meu CV.',
            messages: [],
          },
          {
            id: 't5',
            name: 'Carlos Souza',
            appliedAt: '2026-02-20T15:10:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 10:14',
            unreadCount: 2,
            lastMessage: 'Posso compartilhar meu portfólio?',
            messages: [],
          },
          {
            id: 't6',
            name: 'Fernanda Alves',
            appliedAt: '2026-02-20T16:05:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 19:48',
            unreadCount: 1,
            lastMessage: 'Tenho experiência com design system.',
            messages: [],
          },
          {
            id: 't7',
            name: 'Marcos Vinicius',
            appliedAt: '2026-02-20T17:40:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 08:33',
            unreadCount: 0,
            lastMessage: 'Enviei case de onboarding.',
            messages: [],
          },
          {
            id: 't8',
            name: 'Patricia Gomes',
            appliedAt: '2026-02-20T18:20:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 12:22',
            unreadCount: 4,
            lastMessage: 'Podemos conversar amanhã?',
            messages: [],
          },
          {
            id: 't9',
            name: 'Rafael Nunes',
            appliedAt: '2026-02-20T19:05:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 22:11',
            unreadCount: 0,
            lastMessage: 'Tenho experiência em pesquisa UX.',
            messages: [],
          },
          {
            id: 't10',
            name: 'Tatiane Rocha',
            appliedAt: '2026-02-20T20:30:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 09:55',
            unreadCount: 3,
            lastMessage: 'Enviei meu CV atualizado.',
            messages: [],
          },
          {
            id: 't11',
            name: 'Vinicius Melo',
            appliedAt: '2026-02-20T21:15:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 13:17',
            unreadCount: 1,
            lastMessage: 'Tenho disponibilidade imediata.',
            messages: [],
          },
        ],
      },

      {
        id: 'job-003',
        title: 'Dev Angular Pleno',
        description: 'Manutenção e evolução de front-end web com componentes reutilizáveis e integração com APIs.',
        department: 'Tecnologia',
        location: 'Remoto',
        type: 'CLT',
        status: 'encerrada',
        createdAt: '2026-02-10T18:00:00Z',
        talents: [
          {
            id: 't12',
            name: 'Aline Costa',
            appliedAt: '2026-02-10T09:00:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 20:05',
            unreadCount: 0,
            lastMessage: 'Tenho experiência com Angular 17+.',
            messages: [],
          },
          {
            id: 't13',
            name: 'Diego Ramos',
            appliedAt: '2026-02-10T09:40:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 07:50',
            unreadCount: 2,
            lastMessage: 'Posso atuar como PJ.',
            messages: [],
          },
          {
            id: 't14',
            name: 'Gabriela Teixeira',
            appliedAt: '2026-02-10T10:25:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 15:42',
            unreadCount: 1,
            lastMessage: 'Tenho experiência com RxJS.',
            messages: [],
          },
          {
            id: 't15',
            name: 'Henrique Dias',
            appliedAt: '2026-02-10T11:10:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 18:09',
            unreadCount: 0,
            lastMessage: 'Enviei meu GitHub.',
            messages: [],
          },
          {
            id: 't16',
            name: 'Isabela Moura',
            appliedAt: '2026-02-10T12:00:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 10:37',
            unreadCount: 5,
            lastMessage: 'Tenho case de performance para mostrar.',
            messages: [],
          },
          {
            id: 't17',
            name: 'Lucas Freitas',
            appliedAt: '2026-02-10T12:40:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 14:28',
            unreadCount: 0,
            lastMessage: 'Posso participar de teste técnico.',
            messages: [],
          },
          {
            id: 't18',
            name: 'Marina Barros',
            appliedAt: '2026-02-10T13:25:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'ontem • 23:01',
            unreadCount: 3,
            lastMessage: 'Tenho experiência com Nx monorepo.',
            messages: [],
          },
          {
            id: 't19',
            name: 'Pedro Henrique',
            appliedAt: '2026-02-10T14:05:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 16:03',
            unreadCount: 2,
            lastMessage: 'Tenho disponibilidade para híbrido.',
            messages: [],
          },
          {
            id: 't20',
            name: 'Renata Prado',
            appliedAt: '2026-02-10T14:55:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 11:44',
            unreadCount: 0,
            lastMessage: 'Enviei referências profissionais.',
            messages: [],
          },
          {
            id: 't21',
            name: 'Thiago Martins',
            appliedAt: '2026-02-10T15:35:00Z',
            avatarUrl: 'assets/avatar-default.png',
            lastSeen: 'hoje • 17:10',
            unreadCount: 6,
            lastMessage: 'Podemos marcar entrevista ainda hoje?',
            messages: [],
          },
        ],
      },
    ];
  }
}
